apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: team-a
  sources:
    - repoURL: git@github.com:ryanatfazz/argocd-gitops-example.git
      path: manifests/team-a/apps/nginx/base
      targetRevision: HEAD
      kustomize:
        patches:
          - patch: patches/patch-deployment.yaml
    - repoURL: git@github.com:ryanatfazz/argocd-gitops-example.git
      path: manifests/team-a/apps/nginx/overlays/prod/patches
      targetRevision: HEAD
  destination:
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
