apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: fazzops-announce
spec:
  project: team-a
  sources:
    - repoURL: git@github.com:ryanatfazz/argocd-gitops-example.git
      path: manifests/team-a/apps/simple-app/helm
      targetRevision: HEAD
      helm:
        releaseName: simple-app
        values: |
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
  destination:
    namespace: default
