apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: fazzops-announce
    notifications.argoproj.io/subscribe.on-deleted.slack: fazzops-announce
    notifications.argoproj.io/subscribe.on-deployed.slack: fazzops-announce
    notifications.argoproj.io/subscribe.on-sync-failed.slack: fazzops-announce
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: fazzops-announce
    notifications.argoproj.io/subscribe.on-health-degraded.slack: fazzops-announce
spec:
  project: team-a
  sources:
    - repoURL: git@github.com:ryanatfazz/argocd-gitops-example.git
      path: manifests/team-a/apps/nginx/base
      targetRevision: HEAD
      kustomize:
        patches:
          - patch: |-
              - op: replace
                path: /spec/replicas
                value: 3
            target:
              kind: Deployment
              name: nginx
    - repoURL: git@github.com:ryanatfazz/argocd-gitops-example.git
      path: manifests/team-a/apps/nginx/overlays/prod/additions
      targetRevision: HEAD
  destination:
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
